### ISSUE TITLE
2 led panel

### ISSUE THREAD

**Issue by ghost** [mutex36/esp32_led_panel_i2c#2]
Hello. Thank you for sharing your project. Is it possible control by your code two 32x64 panels?

**Comment by pr8x** [comment]
Hi @k-shyshkin,

I assume you're talking about 64x32 panels? You can chain the rgb panels using the JOUT / JIN connectors. The driver code, however, is currently limited to 64x32 buffers, so that would need to get adjusted. I don't have much time atm, unfortunately.
